# Generated by Django 3.0.6 on 2020-05-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=500)),
                ('post_body', models.TextField()),
                ('post_image', models.ImageField(upload_to='images/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
